name: my_wedding_test
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mysql1: ^0.19.2
  bloc: ^6.1.1
  equatable: ^1.2.6
  flutter_bloc: ^6.1.2
  flutter_svg: ^0.22.0
  google_fonts: ^2.0.0
  carousel_slider: ^3.0.0
  flutter_multi_formatter: ^2.2.0
  image_picker: ^0.8.0+3
  image: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/wedding/
    - assets/logo/
    - assets/svgIcons/
